//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetStruct
{
    using System;
    using System.Collections.Generic;
    
    public partial class Infraestructura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Infraestructura()
        {
            this.GaleriaDeImagenes = new HashSet<GaleriaDeImagenes>();
            this.CategoriaTipo = new HashSet<CategoriaTipo>();
        }
    
        public int idInfraestructura { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string Reseña { get; set; }
        public string Horario { get; set; }
        public string TelefonoContacto { get; set; }
        public string EmailContacto { get; set; }
        public string UrlWeb { get; set; }
        public string MiniaturaWeb { get; set; }
        public Nullable<decimal> Valoracion { get; set; }
        public int idCiudad { get; set; }
    
        public virtual Ciudades Ciudades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GaleriaDeImagenes> GaleriaDeImagenes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoriaTipo> CategoriaTipo { get; set; }
    }
}
