//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetStruct
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NetStructEntities : DbContext
    {
        public NetStructEntities()
            : base("name=NetStructEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CategoriaTipo> CategoriaTipo { get; set; }
        public virtual DbSet<Ciudades> Ciudades { get; set; }
        public virtual DbSet<Continente> Continente { get; set; }
        public virtual DbSet<GaleriaDeImagenes> GaleriaDeImagenes { get; set; }
        public virtual DbSet<Infraestructura> Infraestructura { get; set; }
        public virtual DbSet<Paises> Paises { get; set; }
    }
}
